#! /usr/bin/env python

import sys
import datetime
import vobject

def main():
    try:
        comps = vobject.readComponents(sys.stdin)
        while True:
            comp = comps.next()
            start = comp.vevent.dtstart.value.strftime('%a %d %b %H:%M')
            end = comp.vevent.dtend.value.strftime('%H:%M')
            loc = comp.vevent.location.value
            print "%s-%s, %s" % (start, end, loc)
    except StopIteration:
        pass

if __name__ == '__main__':
    sys.exit(main())
